# Operations

In [1]:
import pandas as pd
import random
import numpy as np
import matplotlib
%matplotlib inline

np.random.seed(42)  # as usual, fixin random seed

In [2]:
df = pd.read_json('./data/sampledf.json')
df.index = ["R{:02d}".format(i) for i in range(len(df))]
df.columns = ["C{:02d}".format(i) for i in range(len(df.columns))]
df

C00  C01  C02  C03  C04  C05  C06  C07  C08  C09
R00   79   19   21   99   35   59   44   25   75   58
R01   25   39   89   66    9   41    6   69   63    3
R02   37   64   31   69   61   97    5   11   76   57
R03   74   61  100    6   58   80   95   50   15   51
R04   79   60   83   85   16    5   16   69    5   20
R05   45   26   73   73  100   60   21   19   95   12
R06   12   29   18   98   62   68   92   29   74   96
R07   36   32   22    4   66   25   63   51   59   14
R08   55   53   89   13   84   87   74    3    2   64
R09   46   74   36   54   21   12   68   33   80   25

### Adding and deleting Series in a DataFrame

In [3]:
df['C10'] = [random.randint(1, 100) for i in range(len(df))]
df

C00  C01  C02  C03  C04  C05  C06  C07  C08  C09  C10
R00   79   19   21   99   35   59   44   25   75   58   46
R01   25   39   89   66    9   41    6   69   63    3   86
R02   37   64   31   69   61   97    5   11   76   57   26
R03   74   61  100    6   58   80   95   50   15   51   14
R04   79   60   83   85   16    5   16   69    5   20   81
R05   45   26   73   73  100   60   21   19   95   12   65
R06   12   29   18   98   62   68   92   29   74   96   73
R07   36   32   22    4   66   25   63   51   59   14   43
R08   55   53   89   13   84   87   74    3    2   64   62
R09   46   74   36   54   21   12   68   33   80   25   80

In [4]:
# caveat when adding a Series:
new_series = pd.Series(list([random.randint(1, 100) for i in range(len(df))]))
new_series

0     68
1     35
2    100
3     32
4     36
5     59
6      5
7     63
8     14
9     79
dtype: int64

In [5]:
df['C10'] = new_series
df

C00  C01  C02  C03  C04  C05  C06  C07  C08  C09  C10
R00   79   19   21   99   35   59   44   25   75   58  NaN
R01   25   39   89   66    9   41    6   69   63    3  NaN
R02   37   64   31   69   61   97    5   11   76   57  NaN
R03   74   61  100    6   58   80   95   50   15   51  NaN
R04   79   60   83   85   16    5   16   69    5   20  NaN
R05   45   26   73   73  100   60   21   19   95   12  NaN
R06   12   29   18   98   62   68   92   29   74   96  NaN
R07   36   32   22    4   66   25   63   51   59   14  NaN
R08   55   53   89   13   84   87   74    3    2   64  NaN
R09   46   74   36   54   21   12   68   33   80   25  NaN

In [6]:
# adding a new Series: mind the index of the DF
new_series.index = df.index
new_series

R00     68
R01     35
R02    100
R03     32
R04     36
R05     59
R06      5
R07     63
R08     14
R09     79
dtype: int64

In [7]:
df['C10'] = new_series
df

C00  C01  C02  C03  C04  C05  C06  C07  C08  C09  C10
R00   79   19   21   99   35   59   44   25   75   58   68
R01   25   39   89   66    9   41    6   69   63    3   35
R02   37   64   31   69   61   97    5   11   76   57  100
R03   74   61  100    6   58   80   95   50   15   51   32
R04   79   60   83   85   16    5   16   69    5   20   36
R05   45   26   73   73  100   60   21   19   95   12   59
R06   12   29   18   98   62   68   92   29   74   96    5
R07   36   32   22    4   66   25   63   51   59   14   63
R08   55   53   89   13   84   87   74    3    2   64   14
R09   46   74   36   54   21   12   68   33   80   25   79

In [8]:
df['C11'] = new_series
df

C00  C01  C02  C03  C04  C05  C06  C07  C08  C09  C10  C11
R00   79   19   21   99   35   59   44   25   75   58   68   68
R01   25   39   89   66    9   41    6   69   63    3   35   35
R02   37   64   31   69   61   97    5   11   76   57  100  100
R03   74   61  100    6   58   80   95   50   15   51   32   32
R04   79   60   83   85   16    5   16   69    5   20   36   36
R05   45   26   73   73  100   60   21   19   95   12   59   59
R06   12   29   18   98   62   68   92   29   74   96    5    5
R07   36   32   22    4   66   25   63   51   59   14   63   63
R08   55   53   89   13   84   87   74    3    2   64   14   14
R09   46   74   36   54   21   12   68   33   80   25   79   79

In [9]:
del df['C11']
df

C00  C01  C02  C03  C04  C05  C06  C07  C08  C09  C10
R00   79   19   21   99   35   59   44   25   75   58   68
R01   25   39   89   66    9   41    6   69   63    3   35
R02   37   64   31   69   61   97    5   11   76   57  100
R03   74   61  100    6   58   80   95   50   15   51   32
R04   79   60   83   85   16    5   16   69    5   20   36
R05   45   26   73   73  100   60   21   19   95   12   59
R06   12   29   18   98   62   68   92   29   74   96    5
R07   36   32   22    4   66   25   63   51   59   14   63
R08   55   53   89   13   84   87   74    3    2   64   14
R09   46   74   36   54   21   12   68   33   80   25   79

In [10]:
del df['C12']

KeyError: 'C12'

In [11]:
# avoid KeyErrors if unsure Series exists
df.drop(['C12'], errors='ignore')

C00  C01  C02  C03  C04  C05  C06  C07  C08  C09  C10
R00   79   19   21   99   35   59   44   25   75   58   68
R01   25   39   89   66    9   41    6   69   63    3   35
R02   37   64   31   69   61   97    5   11   76   57  100
R03   74   61  100    6   58   80   95   50   15   51   32
R04   79   60   83   85   16    5   16   69    5   20   36
R05   45   26   73   73  100   60   21   19   95   12   59
R06   12   29   18   98   62   68   92   29   74   96    5
R07   36   32   22    4   66   25   63   51   59   14   63
R08   55   53   89   13   84   87   74    3    2   64   14
R09   46   74   36   54   21   12   68   33   80   25   79

In [12]:
# getting a subset is simpler than deleting many columns
dfs = df.loc[:, ['C03', 'C05']]
dfs

C03  C05
R00   99   59
R01   66   41
R02   69   97
R03    6   80
R04   85    5
R05   73   60
R06   98   68
R07    4   25
R08   13   87
R09   54   12

In [13]:
dfs['C04'] = [random.randint(1, 100) for i in range(len(df))]

In [14]:
dfs

C03  C05  C04
R00   99   59   52
R01   66   41   26
R02   69   97   99
R03    6   80   41
R04   85    5   13
R05   73   60   79
R06   98   68   94
R07    4   25   15
R08   13   87   90
R09   54   12   82

In [15]:
df

C00  C01  C02  C03  C04  C05  C06  C07  C08  C09  C10
R00   79   19   21   99   35   59   44   25   75   58   68
R01   25   39   89   66    9   41    6   69   63    3   35
R02   37   64   31   69   61   97    5   11   76   57  100
R03   74   61  100    6   58   80   95   50   15   51   32
R04   79   60   83   85   16    5   16   69    5   20   36
R05   45   26   73   73  100   60   21   19   95   12   59
R06   12   29   18   98   62   68   92   29   74   96    5
R07   36   32   22    4   66   25   63   51   59   14   63
R08   55   53   89   13   84   87   74    3    2   64   14
R09   46   74   36   54   21   12   68   33   80   25   79

## Mangle your data

#### RECAP: NumPy Broadcasting

In [16]:
a = np.random.rand(3,1)
a

array([[0.37454012],
       [0.95071431],
       [0.73199394]])

In [17]:
b = np.random.rand(3,1)
b

array([[0.59865848],
       [0.15601864],
       [0.15599452]])

In [18]:
a + b

array([[0.9731986 ],
       [1.10673295],
       [0.88798846]])

In [19]:
a - b

array([[-0.22411837],
       [ 0.79469567],
       [ 0.57599942]])

In [20]:
a * b

array([[0.22422162],
       [0.14832915],
       [0.11418704]])

In [21]:
a / b

array([[0.62563236],
       [6.09359435],
       [4.69243368]])

In [22]:
a + 7

array([[7.37454012],
       [7.95071431],
       [7.73199394]])

In [23]:
b // 2

array([[0.],
       [0.],
       [0.]])

In [24]:
a % 2 == 0

array([[False],
       [False],
       [False]])

In [25]:
a * [4, 5]

array([[1.49816048, 1.87270059],
       [3.80285723, 4.75357153],
       [2.92797577, 3.65996971]])

### Broadcasting in Pandas

In [26]:
sales_data = pd.read_json('./data/blooth_sales_data.json',
                              convert_dates=['birthday', 'orderdate']
                              )
sales_data.head(5)

birthday               customer     name                  orderdate  \
0 1974-01-07    Frontier Industries  Ernesto 2016-10-06 08:21:20.544568   
1 1986-02-05   Bell Telecom Limited    Queen 2016-09-30 08:21:20.544599   
2 1982-07-06            Software Co     Reid 2016-10-05 08:21:20.544622   
3 1971-04-12  Data Design Galaxy Co   Arlene 2016-10-02 08:21:20.544643   
4 1984-12-14           Frontier Inc   Nikita 2016-10-16 08:21:20.544666   

             product  unitprice  units  
0          Star Wars      11.81     27  
1        PlayStation     284.71      1  
2             banana      10.00     49  
3    Thriller record      16.77     48  
4  Harry Potter book       5.65      4

In [27]:
sales_data['turnover'] = sales_data['unitprice'] * sales_data['units']
sales_data.head(5)

birthday               customer     name                  orderdate  \
0 1974-01-07    Frontier Industries  Ernesto 2016-10-06 08:21:20.544568   
1 1986-02-05   Bell Telecom Limited    Queen 2016-09-30 08:21:20.544599   
2 1982-07-06            Software Co     Reid 2016-10-05 08:21:20.544622   
3 1971-04-12  Data Design Galaxy Co   Arlene 2016-10-02 08:21:20.544643   
4 1984-12-14           Frontier Inc   Nikita 2016-10-16 08:21:20.544666   

             product  unitprice  units  turnover  
0          Star Wars      11.81     27    318.87  
1        PlayStation     284.71      1    284.71  
2             banana      10.00     49    490.00  
3    Thriller record      16.77     48    804.96  
4  Harry Potter book       5.65      4     22.60

In [28]:
sales_data['turnover'].mean()

59915.64764605545

In [29]:
sales_data.mean()

unitprice     2329.681343
units           25.808102
turnover     59915.647646
dtype: float64

In [30]:
sales_data['turnover'].sum()

140502193.73000002

In [31]:
sales_data['turnover'].median()

532.14

In [32]:
sales_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2345 entries, 0 to 2344
Data columns (total 8 columns):
birthday     2345 non-null datetime64[ns]
customer     2345 non-null object
name         2345 non-null object
orderdate    2345 non-null datetime64[ns]
product      2345 non-null object
unitprice    2345 non-null float64
units        2345 non-null int64
turnover     2345 non-null float64
dtypes: datetime64[ns](2), float64(2), int64(1), object(3)
memory usage: 146.6+ KB


# Excercise

Calculate the mean without using .mean

In [33]:
# your code here


Find the oldest customer (bithday)

In [34]:
# your code here


### Functions with **`.map(), .apply() .applymap()`**

In [35]:
# map for Series
sales_data['year'] = sales_data['orderdate'].map(lambda x: x.year)
sales_data.head(5)

birthday               customer     name                  orderdate  \
0 1974-01-07    Frontier Industries  Ernesto 2016-10-06 08:21:20.544568   
1 1986-02-05   Bell Telecom Limited    Queen 2016-09-30 08:21:20.544599   
2 1982-07-06            Software Co     Reid 2016-10-05 08:21:20.544622   
3 1971-04-12  Data Design Galaxy Co   Arlene 2016-10-02 08:21:20.544643   
4 1984-12-14           Frontier Inc   Nikita 2016-10-16 08:21:20.544666   

             product  unitprice  units  turnover  year  
0          Star Wars      11.81     27    318.87  2016  
1        PlayStation     284.71      1    284.71  2016  
2             banana      10.00     49    490.00  2016  
3    Thriller record      16.77     48    804.96  2016  
4  Harry Potter book       5.65      4     22.60  2016

In [36]:
# map for Series
sales_data['month'] = sales_data['orderdate'].map(lambda x: x.month)
sales_data.head(5)

birthday               customer     name                  orderdate  \
0 1974-01-07    Frontier Industries  Ernesto 2016-10-06 08:21:20.544568   
1 1986-02-05   Bell Telecom Limited    Queen 2016-09-30 08:21:20.544599   
2 1982-07-06            Software Co     Reid 2016-10-05 08:21:20.544622   
3 1971-04-12  Data Design Galaxy Co   Arlene 2016-10-02 08:21:20.544643   
4 1984-12-14           Frontier Inc   Nikita 2016-10-16 08:21:20.544666   

             product  unitprice  units  turnover  year  month  
0          Star Wars      11.81     27    318.87  2016     10  
1        PlayStation     284.71      1    284.71  2016      9  
2             banana      10.00     49    490.00  2016     10  
3    Thriller record      16.77     48    804.96  2016     10  
4  Harry Potter book       5.65      4     22.60  2016     10

In [37]:
# combine multiple columns
sales_data['year-month'] = sales_data['year'].map(
    str) + sales_data['month'].map(lambda x: "-{:02d}".format(x))

In [38]:
sales_data.head(5)

birthday               customer     name                  orderdate  \
0 1974-01-07    Frontier Industries  Ernesto 2016-10-06 08:21:20.544568   
1 1986-02-05   Bell Telecom Limited    Queen 2016-09-30 08:21:20.544599   
2 1982-07-06            Software Co     Reid 2016-10-05 08:21:20.544622   
3 1971-04-12  Data Design Galaxy Co   Arlene 2016-10-02 08:21:20.544643   
4 1984-12-14           Frontier Inc   Nikita 2016-10-16 08:21:20.544666   

             product  unitprice  units  turnover  year  month year-month  
0          Star Wars      11.81     27    318.87  2016     10    2016-10  
1        PlayStation     284.71      1    284.71  2016      9    2016-09  
2             banana      10.00     49    490.00  2016     10    2016-10  
3    Thriller record      16.77     48    804.96  2016     10    2016-10  
4  Harry Potter book       5.65      4     22.60  2016     10    2016-10

In [39]:
sales_data[['unitprice', 'units']].head()

unitprice  units
0      11.81     27
1     284.71      1
2      10.00     49
3      16.77     48
4       5.65      4

In [40]:
# applymap for df
sales_data[['unitprice', 'units']].applymap(lambda x: np.round(4 * x, 2)).head(5)

unitprice  units
0      47.24    108
1    1138.84      4
2      40.00    196
3      67.08    192
4      22.60     16

In [41]:
sales_data[['unitprice', 'units']].apply(lambda x: np.round(4 * x, 2)).head(5)

unitprice  units
0      47.24    108
1    1138.84      4
2      40.00    196
3      67.08    192
4      22.60     16

#####  Differences of **`.map(), .apply() .applymap()`**

 * **`.map()`**
 >iterate over each element of a DataFrame

In [42]:
sales_data['unitprice'].map(int)[:5]

0     11
1    284
2     10
3     16
4      5
Name: unitprice, dtype: int64

 * **`.apply()`**
 > apply a function on an axis of the DataFrame.

e.g. sum up two cells (hier: unitprice + units)

In [43]:
sales_data[['unitprice', 'units']].apply(sum, axis=1)[:5] # default axis=0

0     38.81
1    285.71
2     59.00
3     64.77
4      9.65
dtype: float64

 * **`.applymap()`** 
 > apply a function on each element of the DataFrame

In [44]:
sales_data[['unitprice', 'units']].applymap(int)[:5]

unitprice  units
0         11     27
1        284      1
2         10     49
3         16     48
4          5      4

#### Remember: a copy of the DF is returned. The DF is not altered.

In [45]:

sales_data.head(5)

birthday               customer     name                  orderdate  \
0 1974-01-07    Frontier Industries  Ernesto 2016-10-06 08:21:20.544568   
1 1986-02-05   Bell Telecom Limited    Queen 2016-09-30 08:21:20.544599   
2 1982-07-06            Software Co     Reid 2016-10-05 08:21:20.544622   
3 1971-04-12  Data Design Galaxy Co   Arlene 2016-10-02 08:21:20.544643   
4 1984-12-14           Frontier Inc   Nikita 2016-10-16 08:21:20.544666   

             product  unitprice  units  turnover  year  month year-month  
0          Star Wars      11.81     27    318.87  2016     10    2016-10  
1        PlayStation     284.71      1    284.71  2016      9    2016-09  
2             banana      10.00     49    490.00  2016     10    2016-10  
3    Thriller record      16.77     48    804.96  2016     10    2016-10  
4  Harry Potter book       5.65      4     22.60  2016     10    2016-10

In [46]:
sales_data['unitprice'] = sales_data['unitprice'].map(lambda x: x * 2)

In [47]:
sales_data.describe()

unitprice        units      turnover    year        month
count   2345.000000  2345.000000  2.345000e+03  2345.0  2345.000000
mean    4659.362687    25.808102  5.991565e+04  2016.0     9.812793
std    13164.655228    14.474110  1.969636e+05     0.0     0.390161
min       10.020000     1.000000  5.080000e+00  2016.0     9.000000
25%       21.320000    13.000000  2.601000e+02  2016.0    10.000000
50%       35.700000    26.000000  5.321400e+02  2016.0    10.000000
75%      979.880000    39.000000  1.016450e+04  2016.0    10.000000
max    49791.260000    50.000000  1.222270e+06  2016.0    10.000000

In [48]:
sales_data['birthday'].describe()

count                    2345
unique                    296
top       1998-04-20 00:00:00
freq                       19
first     1952-02-07 00:00:00
last      1999-05-01 00:00:00
Name: birthday, dtype: object

In [49]:
sales_data['turnover'] = sales_data['turnover'].astype(np.int)
sales_data.head(5)

birthday               customer     name                  orderdate  \
0 1974-01-07    Frontier Industries  Ernesto 2016-10-06 08:21:20.544568   
1 1986-02-05   Bell Telecom Limited    Queen 2016-09-30 08:21:20.544599   
2 1982-07-06            Software Co     Reid 2016-10-05 08:21:20.544622   
3 1971-04-12  Data Design Galaxy Co   Arlene 2016-10-02 08:21:20.544643   
4 1984-12-14           Frontier Inc   Nikita 2016-10-16 08:21:20.544666   

             product  unitprice  units  turnover  year  month year-month  
0          Star Wars      23.62     27       318  2016     10    2016-10  
1        PlayStation     569.42      1       284  2016      9    2016-09  
2             banana      20.00     49       490  2016     10    2016-10  
3    Thriller record      33.54     48       804  2016     10    2016-10  
4  Harry Potter book      11.30      4        22  2016     10    2016-10

In [50]:
# sneak in NaN
sales_data.at[1, 'unitprice'] =  np.NaN
sales_data.at[4, 'unitprice'] =  np.NaN
sales_data.at[3, 'orderdate'] = np.NaN
sales_data.head(5)

birthday               customer     name                  orderdate  \
0 1974-01-07    Frontier Industries  Ernesto 2016-10-06 08:21:20.544568   
1 1986-02-05   Bell Telecom Limited    Queen 2016-09-30 08:21:20.544599   
2 1982-07-06            Software Co     Reid 2016-10-05 08:21:20.544622   
3 1971-04-12  Data Design Galaxy Co   Arlene                        NaT   
4 1984-12-14           Frontier Inc   Nikita 2016-10-16 08:21:20.544666   

             product  unitprice  units  turnover  year  month year-month  
0          Star Wars      23.62     27       318  2016     10    2016-10  
1        PlayStation        NaN      1       284  2016      9    2016-09  
2             banana      20.00     49       490  2016     10    2016-10  
3    Thriller record      33.54     48       804  2016     10    2016-10  
4  Harry Potter book        NaN      4        22  2016     10    2016-10

In [51]:
sales_data[sales_data['unitprice'].isnull()]

birthday              customer    name                  orderdate  \
1 1986-02-05  Bell Telecom Limited   Queen 2016-09-30 08:21:20.544599   
4 1984-12-14          Frontier Inc  Nikita 2016-10-16 08:21:20.544666   

             product  unitprice  units  turnover  year  month year-month  
1        PlayStation        NaN      1       284  2016      9    2016-09  
4  Harry Potter book        NaN      4        22  2016     10    2016-10

In [52]:
sales_data.dropna().head(5)

birthday             customer      name                  orderdate  \
0 1974-01-07  Frontier Industries   Ernesto 2016-10-06 08:21:20.544568   
2 1982-07-06          Software Co      Reid 2016-10-05 08:21:20.544622   
5 1987-08-06   Internet Alpha Inc     Verna 2016-10-03 08:21:20.544687   
6 1962-10-10    Galaxy Industries    Stacia 2016-10-08 08:21:20.544707   
7 1979-03-02         Alpha Agency  Migdalia 2016-09-29 08:21:20.544726   

        product  unitprice  units  turnover  year  month year-month  
0     Star Wars      23.62     27       318  2016     10    2016-10  
2        banana      20.00     49       490  2016     10    2016-10  
5          iPad    2074.84     15     15561  2016     10    2016-10  
6  Rubik’s Cube      31.94     48       766  2016     10    2016-10  
7  Rubik’s Cube      36.34     18       327  2016      9    2016-09

In [53]:
sales_data.head(5)

birthday               customer     name                  orderdate  \
0 1974-01-07    Frontier Industries  Ernesto 2016-10-06 08:21:20.544568   
1 1986-02-05   Bell Telecom Limited    Queen 2016-09-30 08:21:20.544599   
2 1982-07-06            Software Co     Reid 2016-10-05 08:21:20.544622   
3 1971-04-12  Data Design Galaxy Co   Arlene                        NaT   
4 1984-12-14           Frontier Inc   Nikita 2016-10-16 08:21:20.544666   

             product  unitprice  units  turnover  year  month year-month  
0          Star Wars      23.62     27       318  2016     10    2016-10  
1        PlayStation        NaN      1       284  2016      9    2016-09  
2             banana      20.00     49       490  2016     10    2016-10  
3    Thriller record      33.54     48       804  2016     10    2016-10  
4  Harry Potter book        NaN      4        22  2016     10    2016-10

In [54]:
sales_data.fillna(99.99).head(5)

birthday               customer     name                   orderdate  \
0 1974-01-07    Frontier Industries  Ernesto  2016-10-06 08:21:20.544568   
1 1986-02-05   Bell Telecom Limited    Queen  2016-09-30 08:21:20.544599   
2 1982-07-06            Software Co     Reid  2016-10-05 08:21:20.544622   
3 1971-04-12  Data Design Galaxy Co   Arlene                       99.99   
4 1984-12-14           Frontier Inc   Nikita  2016-10-16 08:21:20.544666   

             product  unitprice  units  turnover  year  month year-month  
0          Star Wars      23.62     27       318  2016     10    2016-10  
1        PlayStation      99.99      1       284  2016      9    2016-09  
2             banana      20.00     49       490  2016     10    2016-10  
3    Thriller record      33.54     48       804  2016     10    2016-10  
4  Harry Potter book      99.99      4        22  2016     10    2016-10

In [55]:
sales_data.head()

birthday               customer     name                  orderdate  \
0 1974-01-07    Frontier Industries  Ernesto 2016-10-06 08:21:20.544568   
1 1986-02-05   Bell Telecom Limited    Queen 2016-09-30 08:21:20.544599   
2 1982-07-06            Software Co     Reid 2016-10-05 08:21:20.544622   
3 1971-04-12  Data Design Galaxy Co   Arlene                        NaT   
4 1984-12-14           Frontier Inc   Nikita 2016-10-16 08:21:20.544666   

             product  unitprice  units  turnover  year  month year-month  
0          Star Wars      23.62     27       318  2016     10    2016-10  
1        PlayStation        NaN      1       284  2016      9    2016-09  
2             banana      20.00     49       490  2016     10    2016-10  
3    Thriller record      33.54     48       804  2016     10    2016-10  
4  Harry Potter book        NaN      4        22  2016     10    2016-10

In [56]:
sales_data.fillna(99.99, inplace=True)
sales_data.head(5)

birthday               customer     name                   orderdate  \
0 1974-01-07    Frontier Industries  Ernesto  2016-10-06 08:21:20.544568   
1 1986-02-05   Bell Telecom Limited    Queen  2016-09-30 08:21:20.544599   
2 1982-07-06            Software Co     Reid  2016-10-05 08:21:20.544622   
3 1971-04-12  Data Design Galaxy Co   Arlene                       99.99   
4 1984-12-14           Frontier Inc   Nikita  2016-10-16 08:21:20.544666   

             product  unitprice  units  turnover  year  month year-month  
0          Star Wars      23.62     27       318  2016     10    2016-10  
1        PlayStation      99.99      1       284  2016      9    2016-09  
2             banana      20.00     49       490  2016     10    2016-10  
3    Thriller record      33.54     48       804  2016     10    2016-10  
4  Harry Potter book      99.99      4        22  2016     10    2016-10

---

# There's More

**The Pandas anti-patterns**: fantastic tutorial @ PyCon Otto by Pietro Battiston
     _Pandas, the wrong way_ source: https://pietrobattiston.it/python:pycon